#!/bin/bash

if [ "$1" == "-v" ]
then
	kern=kerns/cubeos-v"$2".dasm16
	stable=kerns/stable-cubeOS.dasm16
fi

temp=cubeOS.dasm16
cat *.cubeos > $temp

if [[ -n $kern ]]
then
	cat $temp > $kern
	cat $temp > $stable
fi

gedit $fin
