#!/bin/bash

if [ "$1" == "-v" ]
then
	kern=kerns/cubeOS-v"$2".dasm16
	binK=kerns/cubeOS-v"$2".bin
	stable=kerns/stable-cubeOS.dasm16
	binS=kerns/binary-cubeOS.bin
fi

temp=cubeOS.dasm16
binT=cubeOS.bin

cat ./LICENSE > $temp
cat ./modules/*.cubeos >> $temp
das -o $binT $temp

if [[ -n $kern ]]
then
	cat $temp > $kern
	cat $temp > $stable
	cp $binT $binK
	cp $binT $binS
fi

dcpu $binT
