#!/bin/bash

exp=";:"
doc="documentation.txt"
timestamp="cubeOS-alpha documentation as of $(date)"

build="cubeOS.dasm16"
#if [ $1 == "-s" ]
#then
#	build="kerns/stable-cubeOS.dasm16"
#fi

echo $timestamp > $doc
grep "^$exp" $build >> $doc
