#!/usr/bin/perl

$infile = $ARGV[0];
open(IN, $infile) || die "Can't open input file:$infile";
$outfile = dcpu/computer/mem.dmp;
open(OUT, ">$outfile")|| die "Can't open output file:$outfile";

while (<IN>) {
    @line = split;
    foreach $w (@line) {
        print OUT pack("H4", $w);;
    }
}

close IN;
close OUT;
